### PR TITLE
Preliminary Interpoli banner

### PR DESCRIPTION
**Pull request by TheNachoBIT**
This is an initial banner for the README.

This font being used is [Archivo Black](https://fonts.google.com/specimen/Archivo+Black?preview.text=Interpoli)

### CODE REVIEW

**Review by xorgy — APPROVED** [review]
Give it a squash. :+ )

**Comment by waywardmonkeys** [comment]
Going to merge this as a preliminary / initial banner. Not sure where we'll end up over time yet and I haven't run this by @raphlinus at all yet.

**Comment by waywardmonkeys** [comment]
The original comment from the PR as I'm about to change it for a better commit message:

> I got a little bit inspired and decided to make a simple logo for the README.
> 
> Interpoli-Light
> Interpoli-Dark
> 
> What do you guys think? :D
> 
> (PD: This font being used is [Archivo Black](https://fonts.google.com/specimen/Archivo+Black?preview.text=Interpoli))

**Comment by waywardmonkeys** [comment]
Doesn't work in Safari (at least).

**Pull request merged**
